version: "3.8"

services:
  mockssh:
    image: ucphhpc/ssh-mount-dummy:latest
    ports:
      - 2222:22
    volumes:
      - ./data:/data

  python:
    build: . 
    volumes:
      - .:/app
    depends_on:
      - mockssh